# Generated by Django 3.1.2 on 2020-11-08 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20201108_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comments',
            new_name='users',
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, related_name='listing', to='auctions.category'),
        ),
    ]
