# Generated by Django 3.1.2 on 2020-11-08 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201108_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='listing', to='auctions.category'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='comments',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='auctions.comment'),
        ),
    ]
