# Generated by Django 3.1.2 on 2020-11-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='owner',
            field=models.IntegerField(default='0'),
        ),
    ]
