# Generated by Django 3.1.2 on 2020-11-11 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20201110_2140'),
        ('auctions', '0011_auto_20201111_1839'),
    ]

    operations = [
    ]
