# Generated by Django 3.1.2 on 2020-11-11 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20201111_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='listing',
            new_name='listings',
        ),
    ]
