# Generated by Django 3.1.2 on 2020-11-14 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20201111_2302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='owner',
            new_name='owner_id',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='updatedate',
        ),
    ]
