# Generated by Django 3.1.2 on 2020-11-14 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20201114_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='owner_id',
        ),
        migrations.AddField(
            model_name='listing',
            name='owner',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='own_listing', to=settings.AUTH_USER_MODEL),
        ),
    ]
