# Generated by Django 3.1.2 on 2020-11-14 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20201114_0023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
