# Generated by Django 3.1.2 on 2020-11-14 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20201114_0058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='user',
            new_name='userid',
        ),
    ]
