# Generated by Django 3.1.2 on 2020-11-14 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_auto_20201114_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-createdate']},
        ),
    ]
